ARG UBI_VERSION=8
FROM registry.red-soft.ru/ubi${UBI_VERSION}/ubi:latest

RUN dnf install -y --setopt=install_weak_deps=False --nodocs \
    gcc gcc-c++ make cmake \
    perl pkgconf-pkg-config \
    curl ca-certificates \
    tar gzip xz \
    && dnf clean all \
    && rm -rf /var/cache/dnf

ENV RUSTUP_HOME=/opt/rustup
ENV CARGO_HOME=/opt/cargo
ENV PATH="/opt/cargo/bin:${PATH}"

WORKDIR /volume

ARG BUILD_FINGERPRINT

RUN curl --proto '=https' --tlsv1.2 -sSf \
    https://sh.rustup.rs \
    | sh -s -- -y --profile minimal --default-toolchain stable \
    && rustup component add rustfmt clippy \
    && rm -rf "${RUSTUP_HOME}"/toolchains/*/share/doc

LABEL org.redos-rust.build-fingerprint=$BUILD_FINGERPRINT
LABEL org.opencontainers.image.source="https://github.com/hexqnt/redos-rust"
