ARG UBI_VERSION=8
FROM hexq/redos-build-base:ubi${UBI_VERSION}

ENV RUSTUP_HOME=/opt/rustup
ENV CARGO_HOME=/opt/cargo
ENV PATH="/opt/cargo/bin:${PATH}"

WORKDIR /volume

ARG BUILD_FINGERPRINT

RUN curl --proto '=https' --tlsv1.2 -sSf \
    https://sh.rustup.rs \
    | sh -s -- -y --profile minimal --default-toolchain stable \
    && rustup component add rustfmt clippy \
    && rm -rf "${RUSTUP_HOME}"/toolchains/*/share/doc

LABEL org.redos-rust.build-fingerprint=$BUILD_FINGERPRINT
LABEL org.opencontainers.image.source="https://github.com/hexqnt/redos-rust"
